baseURL = "https://pilotcloud.ascon.net"
languageCode = 'en-us'
title = "Pilot-Cloud"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = false

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
   
[params]
  # ВЛОЖЕННОСТЬ МЕНЮ (Необязательно, по умолчанию 6) Установите, сколько уровней оглавления должно отображаться на странице.
  # Используйте false, чтобы скрыть ToC, обратите внимание, 
  # что 0 будет обозначать значение по умолчанию, т.е. 6 (https://gohugo.io/functions/default/)
  # Также можно указать этот параметр для каждой страницы в разделе front matter.
  geekdocToC = 0

  # ЛОГОТИП(Необязательно, по умолчанию static/brand.svg) Задайте путь к логотипу для Geekdoc
  # относительно вашей папки 'static/' folder.
  geekdocLogo = "logo-redsm.png"

  # BUNDLE MENU(Необязательно, по умолчанию false) Визуализируйте меню из файла данных в 'data/menu/main.yaml'.
  # Смотрите также https://geekdocs.de/usage/menus/#bundle-menu.
  geekdocMenuBundle = true

  # (Необязательно, по умолчанию false) Свернуть все пункты меню, не могут быть перезаписаны
  # на страницу, если включена эта опция. Может быть включен для каждой страницы с помощью 'geekdocCollapseSection'.
  geekdocCollapseAllSections = false

  # BUNDLE MENU(Необязательно, по умолчанию true) Показывать ссылки для навигации по страницам внизу каждой
  # страницы (только для связанного меню - bundle menu).
  geekdocNextPrev = false

  # ХЛЕБНЫЕ КРОШКИ(Необязательно, по умолчанию true) Показать панель навигации в виде пути до страницы в верхней части каждой страницы документов.
  # Вы также можете указать этот параметр для каждой страницы в разделе front matter.
  geekdocBreadcrumb = true

  # Репозиторий для редактируемых страниц (Необязательно, по умолчанию none) Установите местоположение исходного репозитория. 
  # Используется для ссылок "Редактировать страницу" (Edit page links).
  # Вы также можете указать этот параметр для каждой страницы в разделе front matter.
  # geekdocRepo = "https://github.com/Lekarjal/pilotcloud.git"

  # (Необязательно, по умолчанию none) Доступно для  ссылок "Редактировать страницу" (Edit page links). 
  # Требуется заданный параметр 'GeekdocRepo'
  # и путь должен указывать на родительский каталог папки 'content'. Например, geekdocEditPath = "edit/main/exampleSite"
  # Вы также можете указать этот параметр для каждой страницы в разделе front matter.
  # geekdocEditPath = "Hugo/Sites/pilotcloud.ascon.net"

  # ПОИСК(Необязательно, по умолчанию true) Включает функцию поиска с помощью flexsearch.
  # Index создается "на лету" и может замедлить работу вашего сайта.
  geekdocSearch = true

  # ПОИСК(Необязательно, по умолчанию false) Отображение результатов поиска с родительской папкой в качестве префикса.
  # Эта опция позволяет различать файлы с одинаковыми именами в разных папках.
  # ВНИМАНИЕ: Этот параметр применяется только в том случае, если 'geekdocSearch = true'.
  geekdocSearchShowParent = true

  # (Необязательно, по умолчанию none) Добавьте ссылку на страницу вашего пользовательского соглашения (Legal Notice) в нижний колонтитул сайта.
  # Это может быть либо удаленный URL-адрес, либо локальный путь к файлу относительно вашего каталога содержимого. Например, https://blog.example.com/legal
  geekdocLegalNotice = "https://pilot.ascon.ru/license-pilotems.pdf"

  # (Необязательно, по умолчанию none) Добавьте ссылку на страницу вашей Политики конфиденциальности (Privacy Policy) в нижний колонтитул сайта..
  # Это может быть либо удаленный URL-адрес, либо локальный путь к файлу относительно вашего каталога содержимого.
  # geekdocPrivacyPolicy = "/privacy"

  # Якоря (Необязательно, по умолчанию true) Добавьте якорную ссылку к заголовкам.
  geekdocAnchor = true

  # Копирование якоря (Необязательно, по умолчанию true) Скопируйте URL-адрес якоря в буфер обмена по щелчку мыши.
  geekdocAnchorCopy = true

  # Отложенная загрузка изображений (Необязательно, по умолчанию true) Включить или отключить отложенную загрузку изображений 
  # для отображаемых изображений по короткому коду 'img'.
  geekdocImageLazyLoading = true

  # (Необязательно, по умолчанию false) Задайте HTMl <base> для .Site.BaseURL, если оно включено.
  # Это может потребоваться если подкаталог используется в Hugos BaseURL.
  # Смотрите https://developer.mozilla.org/de/docs/Web/HTML/Element/base.
  geekdocOverwriteHTMLBase = false

  # Улучшенное отображение на тёмном режиме (Необязательно, по умолчанию false) Автоматическое уменьшение яркости изображений и добавление незначительных оттенков серого,  
  # чтобы избежать ярких пятен при использовании темного режима.
  geekdocDarkModeDim = true

  # Всегда тёмная тема(Необязательно, по умолчанию false) Принудительное использование блоков кода для постоянного отображения тёмной темы.
  geekdocDarkModeCode = false

  # Ссылка "в начало"(Необязательно, по умолчанию true) Отображение ссылки "Назад к началу" (Back to top) в нижнем колонтитуле сайта.
  geekdocBackToTop = true

  # Добавление тэгов в меню (Необязательно, по умолчанию false) Включите или отключите автоматическое добавление тегов для страниц c публикациями на боковую панель навигации.
  geekdocTagsToMenu = false

  # Сортировка меню (Необязательно, по умолчанию 'title') Настройте порядок сортировки элементов для дерева файлов в меню. Возможные варианты 'title', 'linktitle',
  # 'date', 'publishdate', 'expirydate' or 'lastmod'. Каждый параметр также может быть использован с обратным модификатором
  # например, 'title_reverse'.
  geekdocFileTreeSortBy = "title"

  # (Необязательно, по умолчанию none) Добавление надписи "Content licensed under <license>" в нижний коллонтитул сайта.
  # Может использоваться, если вы хотите определить лицензию по умолчанию для своего контента.
  [params.geekdocContentLicense]
    name = "CC BY-SA 4.0"
    link = "https://creativecommons.org/licenses/by-sa/4.0/"
	
#PAGE CONFIGURATION

# Задайте тип 'posts', если вы хотите отображать страницу, как публикация в блоге.
# type = "posts"

# Установите "вес" страницы, чтобы изменить порядок элементов в меню дерева файлов.
#weight = 10

# Установите, сколько уровней оглавления должно отображаться на странице.
# geekdocToC = 3

# Задайте описание для текущей страницы. Оно будет показано в объектах toc-trees.
# geekdocDescription =

# Установите значение false, чтобы скрыть всю левую боковую панель навигации. 
# Будьте осторожны, это может сделать навигацию затруднённой без добавления какой-либо 
# другой навигации на странице.
# geekdocNav = true

# Покажите панель навигации в виде хлебных крошек в верхней части каждой страницы документов.
# geekdocBreadcrumb = false

# Установите местоположение исходного репозитория.
# geekdocRepo = "http://vsc.pilot.ascon.net/pilotbim/cloudservicedocs.git"

# Включить ссылки "Редактировать страницу" (Edit page). Требуется параметр 'GeekdocRepo'
# и путь должен указывать на родительский каталог папки 'content'.edit/main/cloudservicedocs
# geekdocEditPath = "C://git/cloudservicedocs"

# Используется для ссылки "Редактировать страницу" (Edit page), установленной по умолчанию в значение '.File.Path'.
# Может быть перезаписан путем, относящимся к 'geekdocEditPath'
# geekdocFilePath =

# Установите флажок помечать страницу как самостоятельный раздел (только меню дерева файлов).
 geekdocFlatSection = true

# Установите значение true, чтобы скрыть страницу или раздел из бокового меню (только меню дерева файлов).
 geekdocHidden = true

# Установите значение false, чтобы отобразить эту страницу в виде элемента меню дерева файлов, если вы хотите, чтобы она была скрыта на боковой панели.
# ВНИМАНИЕ: Применяется только в том случае, если 'geekdocHidden = true'.
# geekdocHiddenTocTree = true

# Установите значение true, чтобы сделать раздел складным в боковом меню.
# geekdocCollapseSection = true

# Добавить якорную ссылку к заголовкам.
 geekdocAnchor = true

# Если вы защитили некоторые страницы, например, с помощью базовой аутентификации, вы можете захотеть исключить эти страницы
# из файла данных, в противном случае может произойти утечка информации. Установка для этого параметра значения "true" исключит
# страницу из поиска по данным, каналам и пр. (data, feeds, etc.)
# ВНИМАНИЕ: Вместо этого рассмотрите возможность размещения отдельной, полностью защищенной от авторизации статической страницы для секретной информации!
# geekdocProtected = false

# Задайте "left" (по умолчанию), "center" или "right" для настройки выравнивания текста страницы.
# geekdocAlign = "left"

refLinksNotFoundURL = "http://www.bileyg.com"